services:
  pivkeyu-pmbot:
    container_name: pivkeyu-pmbot
    image: pivkeyu/pivkeyu_pmbot:latest
    restart: unless-stopped
    env_file:
     - .env
    volumes:
     - ./data:/app/data
     
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    command: --cleanup --interval 3600 pivkeyu-pmbot
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
